spring:
  datasource:
    username: ${MYSQL_DB_USERNAME:root}
    password: ${MYSQL_DB_PASSWORD:root}
    url: ${MYSQL_DB_URI:jdbc:mysql://127.0.0.1:3306/betnare}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  rabbitmq:
    addresses: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    password: ${RABBIT_MQ_PASSWORD:guest}
    username: ${RABBIT_MQ_USERNAME:guest}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:test}